function computeRaisePlan(s){const info=orbitInfo(s,P[s.owner]),base=Math.max(info.ra,info.r);return[Math.max(185,base+45),270,370].filter(v=>v>base+12)}
function traceOrbit(s,maxPoints=280){const p=P[s.owner],info=orbitInfo(s,p);if(!info.bound||!isFinite(info.a))return[];const period=TAU*Math.sqrt(info.a*info.a*info.a/p.mu),steps=clamp(Math.ceil(period/DT),240,4200),stride=Math.max(1,Math.floor(steps/maxPoints)),b={x:s.x,y:s.y,vx:s.vx,vy:s.vy},pts=[];for(let i=0;i<=steps;i++){if(i%stride===0)pts.push({x:b.x,y:b.y,vx:b.vx,vy:b.vy,t:i*DT});integrateVerlet(b,DT,s.owner)}return pts}
function getOrbitTrace(s){if(!s.orbitCache||s.orbitCacheState!==s.state||s.age-(s.orbitCacheAge||0)>.8){s.orbitCache=traceOrbit(s);s.orbitCacheAge=s.age;s.orbitCacheState=s.state}return s.orbitCache||[]}
function nearestOrbitSample(s,pt){const pts=s.orbitPreview||getOrbitTrace(s);let best=null,bestD=1e9;for(const q of pts){const d=Math.hypot(pt.x-q.x,pt.y-q.y);if(d<bestD){bestD=d;best=q}}return best?{sample:best,distance:bestD}:null}
function selectForPreview(s){if(selectedSat&&selectedSat!==s)clearSelection();selectedSat=s;s.selected=true;s.orbitPreview=traceOrbit(s);s.departure=null;s.previewPlan=null;note('Satellite selected · drag along its orbit to search for a valid transfer window')}
function clearSelection(){if(selectedSat){selectedSat.selected=false;selectedSat.orbitPreview=null;selectedSat.departure=null;selectedSat.previewPlan=null}selectedSat=null;orbitPick=false}
function setDeparturePoint(s,pt){const hit=nearestOrbitSample(s,pt);if(!hit||hit.distance>30)return false;s.departure=hit.sample;s.previewPlan=buildPointTransferPreview(s,hit.sample);if(s.previewPlan)note(`Valid transfer · departure in ${hit.sample.t.toFixed(1)} s · fuel ${Math.ceil(s.previewPlan.totalDv)} · tap satellite to commit`);else note('No valid transfer from this point');return true}
function commitSelectedTransfer(s){if(!s.previewPlan||!s.departure){note('Choose a valid transfer point first');return}s.scheduled={wait:Math.max(.04,s.departure.t),dv:s.previewPlan.dv,preview:s.previewPlan};s.state='scheduled';s.selected=false;s.orbitPreview=null;s.departure=null;s.previewPlan=null;selectedSat=null;note(`Transfer scheduled · departure in ${s.scheduled.wait.toFixed(1)} s`)}
function executeScheduledTransfer(s){const plan=s.scheduled;if(!plan)return;const f=tangentialFrame(s,P[s.owner]);if(!spendPropellant(s,plan.dv,'Transfer injection')){s.scheduled=null;return}s.vx+=f.tx*plan.dv;s.vy+=f.ty*plan.dv;s.state='transfer';s.anchor=null;s.transferAge=0;s.burnFlash=.3;s.scheduled=null;s.burnCount=(s.burnCount||0)+1;note(`Hohmann transfer initiated · fuel ${Math.round(s.propellant)}`)}
function startRaising(s){if(s.type!=='sat'||s.state!=='defense')return;const info=orbitInfo(s,P[s.owner]);s.raisePlan=computeRaisePlan(s);s.raiseIndex=0;s.burnCount=0;s.firstRaise=info.e<.035;s.prevRadial=radialVelocity(s,P[s.owner]);s.raiseDelay=.35;s.state='raising';s.selected=false;s.previewPlan=null;selectedSat=null;note('Transfer committed · waiting for periapsis burn 1')}
function cancelRaising(s){if(s.state!=='raising')return;s.state='defense';s.selected=false;note('Orbit raising paused; satellite remains on defence')}
function raiseBurn(s,targetRa){const p=P[s.owner],f=tangentialFrame(s,p),rp=f.r,a=(rp+targetRa)/2,targetV=Math.sqrt(p.mu*(2/rp-1/a)),vt=s.vx*f.tx+s.vy*f.ty,dv=Math.max(0,targetV-vt);if(!spendPropellant(s,dv,'Orbit-raise burn'))return;s.vx+=f.tx*dv;s.vy+=f.ty*dv;s.burnFlash=.24;s.burnCount++;sparks(s.x,s.y,s.owner?'#ffb0c4':'#a6f3ff',7);note(`Orbit-raise burn ${s.burnCount} · fuel ${Math.round(s.propellant)}`)}
function candidateClosest(s,dv){const enemy=P[1-s.owner],home=P[s.owner],f=tangentialFrame(s,home);let b={x:s.x,y:s.y,vx:s.vx+f.tx*dv,vy:s.vy+f.ty*dv},min=1e9,hitEnemy=false,hitHome=false,escaped=false,pts=[],closest=null;for(let i=0;i<1200;i++){integrateVerlet(b,DT*4,null);if(i%4===0)pts.push([b.x,b.y]);const de=Math.hypot(b.x-enemy.x,b.y-enemy.y),dh=Math.hypot(b.x-home.x,b.y-home.y);if(de<min){min=de;closest={x:b.x,y:b.y,vx:b.vx,vy:b.vy}}if(i>12&&dh<home.r+4){hitHome=true;break}if(de<enemy.r+4){hitEnemy=true;break}if(b.x<-460||b.x>W+460||b.y<-460||b.y>H+460){escaped=true;break}}return{min,hitEnemy,hitHome,escaped,pts,closest}}
function chooseInjectionDv(s){let best={score:1e9,dv:0,min:1e9,pts:[],closest:null};for(let dv=8;dv<=145;dv+=4){const q=candidateClosest(s,dv),score=Math.abs(q.min-108)+(q.hitEnemy?900:0)+(q.hitHome?900:0);if(score<best.score)best={score,dv,min:q.min,pts:q.pts,closest:q.closest,hitEnemy:q.hitEnemy,hitHome:q.hitHome,escaped:q.escaped}}return best}
function captureDvFor(owner,state){if(!state)return Infinity;const p=P[1-owner],f=tangentialFrame(state,p),targetV=Math.sqrt(p.mu/f.r)*.94;return Math.hypot(f.tx*targetV-state.vx,f.ty*targetV-state.vy)}
function buildPointTransferPreview(s,burn){const state={owner:s.owner,x:burn.x,y:burn.y,vx:burn.vx,vy:burn.vy},sol=chooseInjectionDv(state),enemy=P[1-s.owner],captureDv=captureDvFor(s.owner,sol.closest),totalDv=sol.dv+captureDv,valid=!sol.hitEnemy&&!sol.hitHome&&sol.min>=enemy.r+18&&sol.min<=145&&isFinite(captureDv)&&totalDv<=s.propellant;if(!valid)return null;return{transfer:sol.pts,dv:sol.dv,captureDv,totalDv,min:sol.min,burnPoint:[burn.x,burn.y],wait:burn.t,target:1-s.owner}}
function transferWindow(s){const enemy=P[1-s.owner],f=tangentialFrame(s,P[s.owner]),dx=enemy.x-s.x,dy=enemy.y-s.y,L=Math.hypot(dx,dy);return(f.tx*dx+f.ty*dy)/L}
function injectionBurn(s){const f=tangentialFrame(s,P[s.owner]),sol=chooseInjectionDv(s);if(!spendPropellant(s,sol.dv,'Transfer injection'))return;s.vx+=f.tx*sol.dv;s.vy+=f.ty*sol.dv;s.state='transfer';s.anchor=null;s.transferAge=0;s.burnFlash=.28;s.burnCount++;note(`Transfer injection burn · fuel ${Math.round(s.propellant)}`)}
function attemptCapture(s){const target=1-s.owner,p=P[target],f=tangentialFrame(s,p);if(f.r<p.r+16||f.r>155)return false;const rv=radialVelocity(s,p);if(rv>=0)return false;const targetV=Math.sqrt(p.mu/f.r)*.94,dvx=f.tx*targetV-s.vx,dvy=f.ty*targetV-s.vy,dv=Math.hypot(dvx,dvy);if(!spendPropellant(s,dv,'Capture burn'))return false;s.vx+=dvx;s.vy+=dvy;s.state='capturing';s.anchor=target;s.burnFlash=.3;s.enemyStable=0;note(`Capture burn · fuel ${Math.round(s.propellant)}`);return true}
function updateRaising(s,dt){const p=P[s.owner],rv=radialVelocity(s,p);s.raiseDelay=Math.max(0,(s.raiseDelay||0)-dt);const peri=(s.prevRadial<0&&rv>=0)||(s.firstRaise&&s.raiseDelay<=0);if(peri){s.firstRaise=false;if(s.raiseIndex<s.raisePlan.length)raiseBurn(s,s.raisePlan[s.raiseIndex++]);else if(transferWindow(s)>.965)injectionBurn(s);else note('Raised orbit complete · waiting for transfer window')}s.prevRadial=rv}
