function updateSatellite(s,dt){
 s.age+=dt;if(s.burnFlash)s.burnFlash=Math.max(0,s.burnFlash-dt);
 if(s.state==='deploying'){s.collectorDeploy=clamp(s.collectorDeploy+dt/POWER.deployTime,0,1);if(s.collectorDeploy>=1){s.state='defense';s.mode='defence';note(s.owner===0?'Collectors online · defence systems charging':'Enemy collectors deployed');if(s.aiIntent)s.armDelay=.8+Math.random()*1.2}}
 chargeSatellite(s,dt);
 if(s.state==='scheduled'){s.scheduled.wait-=dt;if(s.scheduled.wait<=0)executeScheduledTransfer(s)}
 if(s.armDelay!==undefined){s.armDelay-=dt;if(s.armDelay<=0&&s.state==='defense'){delete s.armDelay;startRaising(s)}}
 if(s.state==='raising')updateRaising(s,dt);
 if(s.state==='transfer'){s.transferAge+=dt;attemptCapture(s)}
 integrateVerlet(s,dt,s.anchor);
 if(s.state==='capturing'){const enemy=orbitInfo(s,P[1-s.owner]);s.enemyStable=enemy.bound?s.enemyStable+dt:Math.max(0,s.enemyStable-dt*2);if(s.enemyStable>.5){s.state='recharging_attack';s.anchor=1-s.owner;note(s.owner===0?'Enemy orbit captured · recharging weapons':'Hostile satellite captured your orbit')}}
 if(s.state==='recharging_attack'&&s.energy>=POWER.attackShot){s.state='attack';s.attackTick=0;note(s.owner===0?'Attack weapons online':'Hostile attack weapons online')}
 if(s.state==='attack'){s.attackTick+=dt;if(s.attackTick>.7&&s.energy>=POWER.attackShot){s.attackTick=0;s.energy-=POWER.attackShot;damage(1-s.owner,POWER.attackDamage,'Powered orbital strike')}}
 if(s.state==='defense'||s.state==='scheduled'){s.defCd-=dt;if(s.defCd<=0){let target=null,best=110;for(const q of craft){if(q.dead||q.owner===s.owner||q.type!=='sat'||!['transfer','capturing','recharging_attack','attack'].includes(q.state))continue;const d=Math.hypot(q.x-s.x,q.y-s.y);if(d<best){best=d;target=q}}if(target&&s.energy>=POWER.weaponShot){s.energy-=POWER.weaponShot;beams.push({x1:s.x,y1:s.y,x2:target.x,y2:target.y,life:.16,col:s.owner?'#ff9ab2':'#7be6ff'});sparks(target.x,target.y,s.owner?'#ff9ab2':'#7be6ff',12);target.dead=true;s.defCd=.8;note(s.owner===0?'Defence weapon fired':'Enemy defence intercepted your transfer')}else s.defCd=.12}}
 if(s.state==='transfer'&&s.transferAge>24)s.state='drifting';
}
function bodyCollisions(b){for(let i=0;i<2;i++){const p=P[i],d=Math.hypot(b.x-p.x,b.y-p.y),radius=b.type==='rocket'?1.8:2.4;if(d<p.r+radius){if(b.type==='rocket'&&b.age<.07&&i===b.owner)continue;const hostile=b.owner!==i,sp=Math.hypot(b.vx,b.vy);sparks(b.x,b.y,b.owner?'#ff7f9d':'#69dcff',hostile?18:10);if(hostile)damage(i,Math.min(26,7+sp*.04),'Transfer impact damage');else damage(i,b.type==='rocket'?4:3,'Launch failure');b.dead=true;if(selectedSat===b)clearSelection();return}}if((b.state==='transfer'||b.state==='drifting')&&(b.x<-430||b.x>W+430||b.y<-430||b.y>H+430)){b.dead=true;if(selectedSat===b)clearSelection()}}
function aiLaunch(){const owner=1;if(fleetCount(owner)>=MAX_SATELLITES){aiTimer=1.5;return}const p=P[owner],t={x:p.x+(Math.random()<.5?-1:1)*45,y:p.y+(Math.random()<.5?-1:1)*(100+Math.random()*100)},plan=launchPlan(owner,t),def=craft.filter(q=>!q.dead&&q.owner===owner&&q.type==='sat'&&q.state==='defense').length,atk=craft.filter(q=>!q.dead&&q.owner===owner&&q.type==='sat'&&['raising','transfer','capturing','attack'].includes(q.state)).length;launchRocket(owner,plan,def>=1||atk===0);aiTimer=4+Math.random()*2.5}
function update(){if(over)return;aiTimer-=DT;if(aiTimer<=0)aiLaunch();for(const b of craft){if(b.dead)continue;if(b.type==='rocket')updateRocket(b,DT);else updateSatellite(b,DT);b.trail.push([b.x,b.y,1]);if(b.trail.length>30)b.trail.shift();for(const t of b.trail)t[2]-=DT*1.7;bodyCollisions(b)}for(let i=0;i<craft.length;i++)for(let j=i+1;j<craft.length;j++){const a=craft[i],b=craft[j];if(!a.dead&&!b.dead&&a.owner!==b.owner&&a.type==='sat'&&b.type==='sat'&&Math.hypot(a.x-b.x,a.y-b.y)<5){sparks((a.x+b.x)/2,(a.y+b.y)/2,'#fff',12);a.dead=b.dead=true}}craft=craft.filter(b=>!b.dead);for(const q of debris){q.life-=DT;q.ang+=q.spin*DT;integrateVerlet(q,DT,q.anchor)}debris=debris.filter(q=>q.life>0);for(const f of particles){f.life-=DT;f.x+=f.vx*DT;f.y+=f.vy*DT;f.vx*=.99;f.vy*=.99}particles=particles.filter(f=>f.life>0);for(const b of beams)b.life-=DT;beams=beams.filter(b=>b.life>0);hud()}
function hud(){ph.textContent=Math.ceil(P[0].h);eh.textContent=Math.ceil(P[1].h);pf.style.width=P[0].h+'%';ef.style.width=P[1].h+'%';pt.textContent=fleetCount(0);et.textContent=fleetCount(1);pd.textContent=craft.filter(b=>!b.dead&&b.owner===0&&b.type==='sat'&&b.state==='defense').length;pa.textContent=craft.filter(b=>!b.dead&&b.owner===0&&b.type==='sat'&&['scheduled','raising','transfer','capturing','recharging_attack','attack'].includes(b.state)).length;ed.textContent=craft.filter(b=>!b.dead&&b.owner===1&&b.type==='sat'&&b.state==='defense').length;ea.textContent=craft.filter(b=>!b.dead&&b.owner===1&&b.type==='sat'&&['scheduled','raising','transfer','capturing','recharging_attack','attack'].includes(b.state)).length}

function drawPath(pts,col,width=1.5,dash=[4,7],alpha=.7){if(!pts||pts.length<2)return;X.save();X.globalAlpha=alpha;X.strokeStyle=col;X.lineWidth=width;X.setLineDash(dash);X.beginPath();for(let i=0;i<pts.length;i++)i?X.lineTo(pts[i][0],pts[i][1]):X.moveTo(pts[i][0],pts[i][1]);X.stroke();X.restore()}
function drawPlanet(p){let glow=X.createRadialGradient(p.x,p.y,p.r*.3,p.x,p.y,p.r*2.1);glow.addColorStop(0,p.col+'44');glow.addColorStop(1,'transparent');X.fillStyle=glow;X.beginPath();X.arc(p.x,p.y,p.r*2.1,0,TAU);X.fill();let gr=X.createRadialGradient(p.x-15,p.y-18,5,p.x,p.y,p.r);gr.addColorStop(0,'#fff');gr.addColorStop(.18,p.col);gr.addColorStop(1,'#18265a');X.fillStyle=gr;X.beginPath();X.arc(p.x,p.y,p.r,0,TAU);X.fill();X.strokeStyle='#ffffff55';X.lineWidth=1.2;X.beginPath();X.arc(p.x,p.y,p.r+5,p.spin<0?-.4:.4,p.spin<0?-2.5:2.5,p.spin>0);X.stroke()}
function drawRocket(b){X.save();X.translate(b.x,b.y);X.rotate(b.flightAngle||0);X.fillStyle='#dfe8f8';X.fillRect(-BOOSTER.len/2,-BOOSTER.w/2,BOOSTER.len,BOOSTER.w);X.fillStyle=b.owner?'#ff6d91':'#58dcff';X.beginPath();X.moveTo(BOOSTER.len/2+2,0);X.lineTo(BOOSTER.len/2,-2);X.lineTo(BOOSTER.len/2,2);X.fill();X.fillStyle='#ffd166';X.beginPath();X.moveTo(-BOOSTER.len/2,0);X.lineTo(-BOOSTER.len/2-5,-1.7);X.lineTo(-BOOSTER.len/2-5,1.7);X.fill();X.restore()}
function drawSat(s){X.save();X.translate(s.x,s.y);X.rotate(Math.atan2(s.vy,s.vx));const deploy=clamp(s.collectorDeploy||0,0,1),panel=2.2+3.2*deploy;X.fillStyle=s.owner?'#ffe0e8':'#dff8ff';X.fillRect(-2.4,-1.4,4.8,2.8);X.fillStyle=s.owner?'#ff6d91':'#58dcff';X.fillRect(-3-panel,-1.7,panel,3.4);X.fillRect(3,-1.7,panel,3.4);X.strokeStyle='#ffffff55';X.lineWidth=.5;X.strokeRect(-3-panel,-1.7,panel,3.4);X.strokeRect(3,-1.7,panel,3.4);const ring=s.state==='deploying'?'#9eb6da':(s.state==='defense'||s.state==='scheduled')?'#76f2aa':s.state==='raising'?'#ffd166':s.state==='attack'?'#ff9b55':s.state==='recharging_attack'?'#ffcf70':s.state==='capturing'?'#d9a7ff':s.state==='transfer'?'#d9a7ff':null;if(ring){X.strokeStyle=ring;X.lineWidth=s.selected?2.2:1.2;X.beginPath();X.arc(0,0,s.selected?8:6+(s.state==='raising'?Math.sin(s.age*8):0),0,TAU);X.stroke()}if(s.burnFlash){X.fillStyle='#b7f7ff';X.beginPath();X.moveTo(-2.8,0);X.lineTo(-8,-1.4);X.lineTo(-8,1.4);X.fill()}X.restore();if(s.state==='deploying'||s.selected||s.state==='raising'||s.state==='recharging_attack'){X.fillStyle='#eaf2ff';X.font='9px system-ui';const label=s.state==='deploying'?`ARRAY ${Math.round(deploy*100)}%`:`E${Math.round(s.energy)} M${s.propellant.toFixed(0)}`;X.fillText(label,s.x+8,s.y-8)}}
