function drawLaunchPreview(){if(!drag)return;const p=P[0],plan=launchPlan(0,dragPoint),start=p.pad,deployAngle=start+plan.dir*1.1,dx=Math.cos(deployAngle)*plan.R,dy=Math.sin(deployAngle)*plan.R,px=p.x+dx,py=p.y+dy;
 const ascent=[];for(let i=0;i<=50;i++){const u=i/50,e=u*u*(3-2*u),a=start+plan.dir*(.1+1.0*e),r=p.r+4+(plan.R-p.r-4)*e;ascent.push([p.x+Math.cos(a)*r,p.y+Math.sin(a)*r])}drawPath(ascent,'#58dcff',2,[3,7],.8);
 const tx=-dy/plan.R*plan.dir,ty=dx/plan.R*plan.dir,b={x:px,y:py,vx:tx*plan.v,vy:ty*plan.v},pts=[];let prevR=plan.R,passedApo=false;for(let i=0;i<2200;i++){integrateVerlet(b,DT,0);if(i%7===0)pts.push([b.x,b.y]);const rr=Math.hypot(b.x-p.x,b.y-p.y);if(rr>prevR)passedApo=true;if(plan.kind==='circular'&&i>900)break;if(plan.kind==='elliptical'&&passedApo&&Math.abs(rr-plan.R)<1.5&&i>100)break;prevR=rr}drawPath(pts,plan.kind==='circular'?'#76f2aa':'#ffd166',2,[5,6],.9);
 X.fillStyle='#fff';X.beginPath();X.arc(px,py,3,0,TAU);X.fill();note(`${plan.orientation} ${plan.kind} · Pe ${Math.round(plan.rp)} · Ap ${Math.round(plan.ra)} · release to launch`)}
function drawSatelliteOrbits(){for(const s of craft){if(s.dead||s.type!=='sat'||s.anchor===null||!['defense','scheduled','raising','capturing','recharging_attack','attack'].includes(s.state))continue;const raw=s===selectedSat?(s.orbitPreview||getOrbitTrace(s)):getOrbitTrace(s),pts=raw.map(q=>[q.x,q.y]);if(pts.length<2)continue;const selected=s===selectedSat,col=s.owner?'#ff8aa6':'#78e7ff';drawPath(pts,col,selected?2.2:1,[],selected?.9:.22)}}
function drawTransferPreview(){if(!selectedSat)return;if(selectedSat.departure){X.save();X.fillStyle=selectedSat.previewPlan?'#ffd166':'#7f889b';X.strokeStyle=selectedSat.previewPlan?'#fff1a6':'#c4cada';X.lineWidth=1.4;X.beginPath();X.arc(selectedSat.departure.x,selectedSat.departure.y,5,0,TAU);X.fill();X.stroke();X.restore()}const q=selectedSat.previewPlan;if(!q)return;drawPath(q.transfer,'#d9a7ff',2.2,[7,6],.95);X.fillStyle='#ffd166';X.beginPath();X.arc(q.burnPoint[0],q.burnPoint[1],3,0,TAU);X.fill()}
function draw(){X.setTransform(C.q*sc,0,0,C.q*sc,C.q*ox,C.q*oy);X.fillStyle='#050713';X.fillRect(0,0,W,H);X.fillStyle='#dfe9ff';for(const s of stars){X.globalAlpha=s[3];X.beginPath();X.arc(s[0],s[1],s[2],0,TAU);X.fill()}X.globalAlpha=1;drawPlanet(P[0]);drawPlanet(P[1]);drawSatelliteOrbits();drawLaunchPreview();drawTransferPreview();for(const b of craft){X.strokeStyle=b.owner?'#ff6d9144':'#58dcff44';X.beginPath();for(let i=0;i<b.trail.length;i++){const t=b.trail[i];i?X.lineTo(t[0],t[1]):X.moveTo(t[0],t[1])}X.stroke();b.type==='rocket'?drawRocket(b):drawSat(b)}for(const q of debris){X.save();X.translate(q.x,q.y);X.rotate(q.ang);X.fillStyle='#8796af';X.fillRect(-2.5,-1,5,2);X.restore()}for(const f of particles){X.globalAlpha=clamp(f.life*2,0,1);X.fillStyle=f.col;X.beginPath();X.arc(f.x,f.y,f.r,0,TAU);X.fill()}X.globalAlpha=1;for(const b of beams){X.globalAlpha=b.life/.16;X.strokeStyle=b.col;X.lineWidth=1.4;X.beginPath();X.moveTo(b.x1,b.y1);X.lineTo(b.x2,b.y2);X.stroke()}X.globalAlpha=1}
function loop(t){acc+=Math.min(.05,(t-last)/1000);last=t;while(acc>=DT){update();acc-=DT}draw();requestAnimationFrame(loop)}
function hitOwnSat(pt){let best=null,d=24;for(const s of craft){if(s.dead||s.owner!==0||s.type!=='sat'||!['defense','scheduled'].includes(s.state))continue;const z=Math.hypot(pt.x-s.x,pt.y-s.y);if(z<d){d=z;best=s}}return best}
C.onpointerdown=e=>{const q=world(e),sat=hitOwnSat(q);if(sat){if(sat.state==='scheduled'){note(`Transfer already scheduled · departure in ${Math.max(0,sat.scheduled.wait).toFixed(1)} s`);return}if(selectedSat===sat){commitSelectedTransfer(sat);return}selectForPreview(sat);return}if(selectedSat){setDeparturePoint(selectedSat,q);return}const p=P[0];if(!over&&Math.hypot(q.x-p.x,q.y-p.y)<p.r+36){if(fleetCount(0)>=MAX_SATELLITES){note('Fleet limit reached: maximum 10 satellites');return}drag=true;dragPoint=q;C.setPointerCapture(e.pointerId)}};
C.onpointermove=e=>{if(drag)dragPoint=world(e)};C.onpointerup=e=>{if(!drag)return;drag=false;const q=world(e),plan=launchPlan(0,q);if(Math.hypot(q.x-P[0].x,q.y-P[0].y)>18&&launchRocket(0,plan,false))note(`${plan.orientation} ${plan.kind} launch committed`)};
helpBtn.onclick=()=>{const open=helpPanel.classList.toggle('open');helpBtn.textContent=open?'Close':'Help';helpBtn.setAttribute('aria-expanded',String(open))};
resetBtn.onclick=()=>{craft=[];debris=[];particles=[];beams=[];clearSelection();P[0].h=P[1].h=100;aiTimer=2.4;over=false;helpPanel.classList.remove('open');helpBtn.textContent='Help';helpBtn.setAttribute('aria-expanded','false');note('New battle');hud()};
hud();requestAnimationFrame(loop);
